# Generated by Django 2.1.7 on 2020-04-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200412_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='details',
            field=models.CharField(default='No profile details set yet by the user', max_length=200),
        ),
    ]
