# Generated by Django 2.1.7 on 2020-04-02 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('region', models.CharField(default='non selected', max_length=50)),
                ('food_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='food_photos')),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDescription',
            fields=[
                ('description', models.TextField(max_length=400)),
                ('food_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_type', serialize=False, to='cookella.FoodType')),
                ('ingredient', models.TextField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
