# Generated by Django 2.1.7 on 2020-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='region',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Asia', 'Asia'), ('North America', 'North America'), ('South America', 'South America'), ('Australia', 'Australia'), ('Oceania', 'Oceania')], default='Africa', max_length=30),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
    ]
