# Generated by Django 2.1.7 on 2020-04-13 15:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0002_auto_20200412_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='continent',
        ),
        migrations.AddField(
            model_name='fooddescription',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
