# Generated by Django 2.1.7 on 2020-04-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0003_auto_20200413_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fooddescription',
            name='ingredient',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='fooddescription',
            name='note',
            field=models.CharField(blank=True, max_length=1450),
        ),
    ]
