# Generated by Django 2.1.7 on 2020-04-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0004_auto_20200416_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('comment_published', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('comment_created',),
            },
        ),
        migrations.CreateModel(
            name='FoodRecipe',
            fields=[
                ('recipe', models.TextField()),
                ('food_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_type', serialize=False, to='cookella.FoodType')),
                ('ingredient', models.TextField(max_length=600)),
                ('upvotes', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=1450)),
            ],
        ),
        migrations.RemoveField(
            model_name='fooddescription',
            name='food_type',
        ),
        migrations.DeleteModel(
            name='FoodDescription',
        ),
        migrations.AddField(
            model_name='foodcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_comments', to='cookella.FoodRecipe'),
        ),
    ]
