# Generated by Django 2.1.7 on 2020-04-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0005_auto_20200416_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcomments',
            name='post',
        ),
        migrations.RenameField(
            model_name='foodrecipe',
            old_name='upvotes',
            new_name='upvote',
        ),
        migrations.DeleteModel(
            name='FoodComments',
        ),
    ]
