# Generated by Django 2.1.7 on 2020-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0006_auto_20200417_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
