# Generated by Django 2.1.7 on 2020-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0007_auto_20200425_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
