# Generated by Django 2.1.7 on 2020-04-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0008_auto_20200425_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='contributors',
            field=models.CharField(default='admins', max_length=150),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='note',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
