# Generated by Django 2.1.7 on 2020-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0009_auto_20200430_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='contributors',
            new_name='contributor',
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='date_added'),
        ),
    ]
