# Generated by Django 2.1.7 on 2020-05-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0010_auto_20200501_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='contributor',
            field=models.CharField(default='admin', max_length=150),
        ),
    ]
