# Generated by Django 2.1.7 on 2020-05-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0011_auto_20200501_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='food_image',
            field=models.ImageField(default='default.jpg', upload_to='food_photos'),
        ),
    ]
