# Generated by Django 3.1.1 on 2020-09-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookella', '0016_auto_20200502_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='ingredient',
            field=models.TextField(max_length=1000),
        ),
    ]
