# Generated by Django 2.1.7 on 2020-04-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
    ]
