# Generated by Django 3.1.1 on 2020-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201106_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_state',
            field=models.BooleanField(default=False, help_text='this set flag when page refreshes even after updating likes with json request'),
        ),
    ]
