# Generated by Django 3.1.1 on 2020-11-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_like_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_state',
            field=models.BooleanField(help_text='this set flag when page refreshes even after updating likes with json request'),
        ),
    ]
