# Generated by Django 3.1.1 on 2020-11-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201109_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_state',
        ),
    ]
