# Generated by Django 3.1.1 on 2020-11-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_like_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
